const data = [
  {
    id: 1,
    name: "Black hoodie",
    image: "download.jpg",
    price: 20,
    features: {
      category: "hoodies",
      color: "black",
      size: ["L", "XL", "XXL", "S", "M"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 2,
    name: "Red hoodie",
    image: "download.jpg",
    price: 30,
    description: "Red hoodie",
    features: {
      category: "hoodies",
      color: "Red",
      size: ["XL", "XXL"],
    },
    instock: true,
    quantity: 20,
    cart: false,
  },
  {
    id: 3,
    name: "Black Shirt",
    image: "download.jpg",
    price: 60,
    description: "Black Shirt",
    features: {
      category: "shirts",
      color: "black",
      size: ["L", "XL", "XXL", "XXXL", "M"],
    },
    instock: true,
    quantity: 20,
    cart: false,
  },
  {
    id: 4,
    name: "White shirt",
    image: "download.jpg",
    price: 20,
    description: "White Shirt",
    features: {
      category: "shirts",
      color: "white",
      size: ["L", "XL", "M"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 5,
    name: "Black sweaters",
    image: "download.jpg",
    price: 20,
    description: "Black sweaters",
    features: {
      category: "sweaters",
      color: "Black",
      size: ["M", "L", "XL", "XXL", "XXXL"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 6,
    name: "Green sweaters",
    image: "download.jpg",
    price: 40,
    description: "Green sweaters",
    features: {
      category: "sweaters",
      color: "green",
      size: ["L", "XL", "XXL"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 7,
    name: "Blue T-shirt",
    image: "download.jpg",
    price: 40,
    description: "Blue T-shirt",
    features: {
      category: "tshirts",
      color: "blue",
      size: ["L", "XL", "XXL", "M"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 8,
    name: "Black T-shirt",
    image: "download.jpg",
    price: 40,
    description: "Black T-shirt",
    features: {
      category: "tshirts",
      color: "black",
      size: ["L", "XL", "XXL", "M"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 9,
    name: "Yellow shirt",
    image: "download.jpg",
    price: 40,
    description: "Yellow shirt",
    features: {
      category: "shirt",
      color: "Yellow",
      size: ["L", "XL", "XXL"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 10,
    name: "Blue T-shirt",
    image: "download.jpg",
    price: 40,
    description: "Blue T-shirt",
    features: {
      category: "tshirt",
      color: "blue",
      size: ["L", "XL", "XXL", "M"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 11,
    name: "Black Sweatshirt",
    image: "download.jpg",
    price: 30,
    description: "black sweatshirt",
    features: {
      category: "sweatshirt",
      color: "black",
      size: ["L", "XL", "XXL", "M"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 12,
    name: "Pink Sweatshirt",
    image: "download.jpg",
    price: 40,
    description: "Pink sweatshirt",
    features: {
      category: "sweatshirt",
      color: "pink",
      size: ["L", "XL", "XXL", "S"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 13,
    name: "Black Jacket",
    image: "download.jpg",
    price: 40,
    description: "Black Jacket",
    features: {
      category: "jacket",
      color: "black",
      size: ["L", "XL", "XXL", "S"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 14,
    name: "Pink shirt",
    image: "download.jpg",
    price: 40,
    description: "Pink shirt",
    features: {
      category: "shirt",
      color: "pink",
      size: ["L", "XL", "XXL", "S"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
  {
    id: 15,
    name: "Pink Sweatshirt",
    image: "download.jpg",
    price: 40,
    description: "Pink sweatshirt",
    features: {
      category: "sweatshirt",
      color: "black",
      size: ["L", "XL", "XXL", "S"],
    },
    instock: true,
    quantity: 10,
    cart: false,
  },
];

export default data;
